config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'

  resources :personals, except: :index

  resources :businesses, except: :index

  resources :wallets, except: :index

  resources :transactions, only: [:create, :destroy] #DOUBLE CHECK TO BE SURE.

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get "help", to: "pages#help", as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'about', to: 'pages#about', as: 'about'
  get 'postregistration', to: 'pages#postregistration', as: 'postregistration'
  get 'personalqr/:uuid', to: 'pages#personalqr', as: 'personalqr'
  get 'businessqr/:uuid', to: 'pages#businessqr', as: 'businessqr'
  get 'registered', to: 'pages#registered', as: 'registered'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def index
  end

  def new
    # @user = current_user
    @business = Business.new
  end



  def create
    @business = Business.new(business_params)
    @business.user_id = current_user.id
    if @business.save
      flash[:notice] = "Your business profile was successfully created!  Don't forget to make a personal profile as well if you haven't!"
      redirect_to dashboard_path
    else
      flash[:notice] = "There was an error, please try again!"
      render "new"
    end
  end

  def show
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      flash[:notice] = "Your business profile was successfully edited!"
      redirect_to dashboard_path
    else
      flash[:notice] = "There was an error, please try again!"
      render 'edit'
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    flash[:notice] = "Your business profile was successfully deleted!"
    redirect_to root_path
  end

  def edit
    @business = Business.find(params[:id])
  end




  private

  def business_params
    params.require(:business).permit( :first_name, :last_name, :linked_in, :photo, :work_phone, :work_email, :occupation, :job_title, :company, :user_id, :user)
  end
end

app/views/businesses/edit.html.erb
<div class="container-small mt-3">
<div class="row align-items-center justify-content-center">
<h2>Please provide the business information about yourself you are comfortable with!</h2>
</div>

<div class="row align-items-center justify-content-center">
<%= simple_form_for @business do |f|%>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :linked_in, label: "Linked In User Name", placeholder: "Linkedin.com/" %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.input :work_phone %>
<%= f.input :work_email %>
<%= f.input :occupation %>
<%= f.input :job_title %>
<%= f.input :company %>
<div style="text-align:center">
<%= f.button :submit, 'Submit', class: 'btn btn-danger'%>
</div>
<% end %>
</div>
</div>

app/views/businesses/new.html.erb
<div class="container-small mt-3">
<div class="row align-items-center justify-content-center">
<h2>Please provide the business information about yourself you are comfortable with!</h2>
</div>

<div class="row align-items-center justify-content-center">
<%= simple_form_for @business do |f|%>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :linked_in, label: "Linked In User Name", placeholder: "Linkedin.com/" %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.input :work_phone %>
<%= f.input :work_email %>
<%= f.input :occupation %>
<%= f.input :job_title %>
<%= f.input :company %>
<div style="text-align:center">
<%= f.button :submit, 'Submit', class: 'btn btn-danger'%>
</div>
<% end %>
</div>
</div>

app/views/businesses/show.html.erb
<div class="container pt-3">

 <% if current_user && current_user.wallet && @business.user != current_user && [Transaction.where(sender_id: current_user.wallet.id, receiver_id: @business.user.wallet.id, kind: "business"), Transaction.where(receiver_id: current_user.wallet.id, sender_id: @business.user.wallet.id, kind: "business")].flatten.empty? %>
 <div class="row align-items-center justify-content-center py-1">
  <h5>Here is the business information for your new friend!  Save it to your wallet!
  <div class="row align-items-center justify-content-center py-3">
<%= link_to 'Add to wallet', transactions_path(@business), method: :post, class: 'btn btn-danger' %>
  </div>
<% elsif !current_user%>
<div class="row align-items-center justify-content-center py-1">
  <h5>Here is the business information for your new friend!  Make a free account so you can save their information for later use!</h5>
  </div>
<div class="row align-items-center justify-content-center py-3">
  <%= link_to 'Make an account!', new_user_registration_path, method: :get, class: 'btn btn-danger' %>
  </div>
  <% end %>


<div class="container-small">

<p class="card-text row align-items-center justify-content-center pt-2">
<% if @business.photo? %><%= cl_image_tag @business.photo, height: 135, width: 180, crop: :fill, class: "img-raised rounded-circle img-fluid show-photos" %></p>
<% else %>
<%=image_tag "https://usergroups.anaplan.com/static/images/placeholder_avatar.png", height: 135, width: 180, crop: :fill, class: "img-raised rounded-circle img-fluid show-photos" %></p>
<% end %>
<% if %>

<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.first_name? && @business.last_name? %>
<strong><%= @business.first_name %> <%= @business.last_name %></strong>
</p>
<% end %>
<% else %>
 </div>
</div>


<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.first_name? %>
First name: <%= @business.first_name %><%= @business.last_name %>
</p>
<% end %>


<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.last_name? %>
Last name: <%= @business.last_name %>
</p>
<% end %>
<% end %>


<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.work_email? %>
Work email: <%= @business.work_email %>
</p>
<% end %>

<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.work_phone? %>
Work phone: <%= @business.work_phone %>
</p>
<% end %>


<div class="d-flex justify-content-center">
  <div class="d-flex justify-content-between" style="width: 80%;">
<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.occupation? %>
</p>
Occupation: <%= @business.occupation %>
<% end %>
 </div>
</div>

<div class="d-flex justify-content-center">
  <div class="d-flex justify-content-between" style="width: 80%;">
<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.linked_in? %>
<strong>Linked In: &nbsp;</strong><%= @business.linked_in %>
</p>
<%= link_to_image( 'linkedin.png', "http://www.linkedin.com/in/#{@business.linked_in}", class: "logos")%>
<% end %>
 </div>
</div>

<div class="d-flex justify-content-center">
  <div class="d-flex justify-content-between" style="width: 80%;">
<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.company? %>
</p>
Company: <%= @business.company %>
<% end %>
 </div>
</div>

<div class="d-flex justify-content-center">
  <div class="d-flex justify-content-between" style="width: 80%;">
<p class="card-text row align-items-center justify-content-center align-items-center" >
<% if @business.job_title? %>
</p>
Job title: <%= @business.job_title %>
<% end %>
 </div>
</div>
</div>
</div>