config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'

  resources :personals, except: :index

  resources :businesses, except: :index

  resources :wallets, except: :index

  resources :transactions, only: [:create, :destroy] #DOUBLE CHECK TO BE SURE.

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get "help", to: "pages#help", as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'about', to: 'pages#about', as: 'about'
  get 'postregistration', to: 'pages#postregistration', as: 'postregistration'
  get 'personalqr/:uuid', to: 'pages#personalqr', as: 'personalqr'
  get 'businessqr/:uuid', to: 'pages#businessqr', as: 'businessqr'
  get 'registered', to: 'pages#registered', as: 'registered'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/95/76/1a/95761ad0692a4f23d0912f25295ed090.jpg);">
  <div class="container">
    <h1>Welcome to QmyR!</h1>
      <h1>Register here to organize and share your contact information more easily!</h1>
      <%= link_to 'Make an account!', new_user_registration_path, method: :get, class: 'btn btn-danger' %>
  </div>
</div>

app/views/shared/_business_wallet_card.html.erb
<div class="business-wallet-card">
  <% if business.photo? %>
  <img src=<%= business.photo %> />
  <% else %>
    <%= image_tag("https://usergroups.anaplan.com/static/images/placeholder_avatar.png") %>
  <% end %>
  <div class="card-product-infos">
    <h2><%= business.first_name %> <%= business.last_name %></h2>
    <p><%= business.occupation %> <strong> <%= business.company %></strong> <%= business.job_title %></p>
    <p>You met each other on <strong> <%= business.transaction_time %></strong></p>
    <p><%= link_to 'See this business contact', business_path(business.id)  %></p>
    <%= link_to 'Delete from wallet', transaction_path(business.user.transactions.find { |tr| tr.sender_id == business.user.wallet.id || tr.receiver_id == business.user.wallet.id }), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://i.pinimg.com/originals/95/76/1a/95761ad0692a4f23d0912f25295ed090.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wallet", wallet_path(current_user.id), class: "nav-link" %>
        </li>
       
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_personal_wallet_card.html.erb
<div class="personal-wallet-card">
  <% if personal.photo? %>
    <img src=<%= personal.photo %> />
  <% else %>
    <%= image_tag("https://usergroups.anaplan.com/static/images/placeholder_avatar.png") %>
  <% end %>
  <div class="card-product-infos">
    <h2><%= personal.first_name %> <%= personal.last_name %></h2>
    <p>You met each other on <strong><%= personal.transaction_time %></strong></p>
    <p><%= link_to 'See this personal contact', personal_path(personal.id)  %></p>
    <%= link_to 'Delete from wallet', transaction_path(personal.user.transactions.find { |tr| tr.sender_id == personal.user.wallet.id || tr.receiver_id == personal.user.wallet.id }), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>