config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'

  resources :personals, except: :index

  resources :businesses, except: :index

  resources :wallets, except: :index

  resources :transactions, only: [:create, :destroy] #DOUBLE CHECK TO BE SURE.

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get "help", to: "pages#help", as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'about', to: 'pages#about', as: 'about'
  get 'postregistration', to: 'pages#postregistration', as: 'postregistration'
  get 'personalqr/:uuid', to: 'pages#personalqr', as: 'personalqr'
  get 'businessqr/:uuid', to: 'pages#businessqr', as: 'businessqr'
  get 'registered', to: 'pages#registered', as: 'registered'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/businessqr.html.erb
<div class="row align-items-center justify-content-center py-1 ">
<h3>Show this QR to your new business connection</h3>
</div>
<div class="row align-items-center justify-content-center py-1 ">
<h3>Or</h3>
</div>
<div class="row align-items-center justify-content-center py-1 ">
<h3>Share this page with them: </h3>
</div>
<div class="row align-items-center justify-content-center py-1">
<%= social_share_button_tag(@business) %>
</div>

<%# qr = RQRCode::QRCode.new( 'my string to generate', :size => 4, :level => :h )
puts qr.to_s %>

<%# @qr = RQRCode::QRCode.new("http://localhost:3000/", size: 7, level: :h) %>
<%# conditional if logged in as user with profiles or not for auto add??
<% if Rails.env.production? %>
<div class="row align-items-center justify-content-center py-3">
<%= render_qr_code("http://qmyr.herokuapp.com/businesses/#{current_user.business.id}/") %>
<% else %>
<%= render_qr_code("http://localhost:3000/businesses/#{current_user.business.id}/") %>
</div>
<% end %>

<%#= qr = RQRCode::QRCode.new("http://localhost:3000/businesses/#{current_user.business.id}/") %>

app/views/pages/dashboard.html.erb
<div class="row align-items-center justify-content-center">
<div class="row">
<h3 class=" py-2">Your dashboard </h3>
</div>
</div>


<div class="container-dashboard">

<div class="row align-items-center justify-content-center py-2">
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Personal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Business</a>
  </li>
<li class="nav-item">
    <a class="nav-link" id="account-tab" data-toggle="tab" href="#account" role="tab" aria-controls="account" aria-selected="false">Account</a>
  </li>
</ul>
</div>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class=" row align-items-center justify-content-center">
        <div class="col-sm-6">


<% if !@user.personal %>
<div class="row align-items-center justify-content-center">
<div class="row">
<p><strong>Create your personal profile as well!</strong></p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>New personal profile <%= link_to 'New Personal', new_personal_path, class: 'btn btn-danger'%> </p>
</div>
</div>
<% end %>

<% if @user.personal %>

<div class="row align-items-center justify-content-center">
<div class="row">
<p><strong>Share your personal profile </strong><%= link_to 'Share Personal', personalqr_path(current_user.personal), class: 'btn btn-danger' %> </p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>See your personal profile <%= link_to 'See Personal', personal_path(current_user.personal), class: 'btn btn-danger' %> </p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>Edit your personal profile <%= link_to 'Edit Personal', edit_personal_path(current_user.personal), class: 'btn btn-danger' %> </p>
</div>
</div>

<% end %>

        </div>
      </div>
  </div>

  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="row align-items-center justify-content-center">
        <div class="col-sm-6">


<% if !@user.business %>
<div class="row align-items-center justify-content-center">
<div class="row">
<p><strong>Create your business profile as well!</strong></p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>New business profile <%= link_to 'New Business', new_business_path, class: 'btn btn-danger' %> </p>
</div>
</div>
<% end %>

<% if @user.business %>

<div class="row align-items-center justify-content-center">
<div class="row">
<p><strong>Share your business profile </strong><%= link_to 'Share Business', businessqr_path(current_user.business), class: 'btn btn-danger' %> </p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>See your business profile <%= link_to 'See Business', business_path(current_user.business), class: 'btn btn-danger' %> </p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>Edit your business profile <%= link_to 'Edit Business', edit_business_path(current_user.business), class: 'btn btn-danger' %> </p>
</div>
</div>

<% end %>

         </div>
        </div>
    </div>


  <div class="tab-pane fade" id="account" role="tabpanel" aria-labelledby="account-tab">
      <div class="row align-items-center justify-content-center">
        <div class="col-sm-6">

<div class="row align-items-center justify-content-center">
<div class="row">
<p>See your connection wallet <%= link_to 'Wallet', wallet_path(current_user.id), class: 'btn btn-danger' %> </p>
</div>
</div>


<div class="row align-items-center justify-content-center">
<div class="row">
<p>Delete your account <%= link_to 'Delete account', user_registration_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>Log out <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></p>
</div>
</div>

    </div>
  </div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<%= render partial: 'shared/banner'  %>

<div class="banner_lower">
<div class="row align-items-center justify-content-center">
<div class="row">
<p><h2>Why join?</h2></p>
<br>
<p>Today, we have endless ways in order to keep in contact with each other.  It can be hard to</p>
</div>
</div>
</div>

<div class="banner_lower">
<div class="row align-items-center justify-content-center">
  <h2>Here's how it works</h2>
    <div class="col-sm-4">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
    <div class="col-sm-4">
      Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
    </div>
    <div class="col-sm-4">
      Did it work?
    </div>
</div>
</div>


<%# <h3>Welcome!  Please... </h3> %>

<%# if !current_user %>
 <%# <p>Create an account here!<%= link_to "Sign up!", new_user_registration_path, class: 'btn btn-danger'</p> %>
<%# else %>
<%# <p>= Welcome back user.username, go to your dashboard: link_to "Dashboard", dashboard_path(current_user), class: 'btn btn-danger'  </p> %>
<%# end %>

app/views/pages/personalqr.html.erb
<div class="row align-items-center justify-content-center py-1">
<h3>Show this QR to your new personal connection</h3>
</div>
<div class="row align-items-center justify-content-center py-1">
<h3>Or</h3>
</div>
<div class="row align-items-center justify-content-center py-1">
<h3>Share this page with them: </h3>
</div>
<div class="row align-items-center justify-content-center py-1">
<%= social_share_button_tag(@personal) %>
</div>

<% if Rails.env.production? %>
<div class="row align-items-center justify-content-center py-3">
<%= render_qr_code("http://qmyr.herokuapp.com/personals/#{current_user.personal.id}/") %>
<% else %>
<%= render_qr_code("http://localhost:3000/personals/#{current_user.personal.id}/") %>
</div>
<% end %>

app/views/pages/postregistration.html.erb
Thank you for registering!

app/views/pages/registered.html.erb
<div class="container-small mt-3">
<div class="row align-items-center justify-content-center py-1">
<div class="container">
<div style="text-align:center">
<p>Congratulations on signing up for QmyR!  </p>
<p>You'll now be able to keep in better touch with your business + personal connections!</p>
<br>
<p>Before proceeding, please first create either a business profile or a personal profile.</p>
<br>
<p>After you make one of the profiles, you can make the other one from your user dashboard.</p>
<br>
<p>In order for the app to work properly, please make both profiles, even if you intend to only use one of them!</p>
<p><h5><strong>Important!</strong></h5></p>
<p><h5><strong>At the current early stage of development, the app is not present in the Apple store or any Android store platforms!</strong></h5></p>
<br>
<p><h5><strong>To have this app on your phone:  </strong></h5></p>
<p><h5><strong>For iOS users:  On Safari, click the share button on the bottom middle portion of the browser, then select Add To Home Screen</strong></h5></p>
<p><h5><strong>For Android users:  Once the app has loaded, click on the add to homescreen shortcut on Firefox, or click on menu dots, then Add to homescreen for Chrome</strong></h5></p>
</div>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p><h5><strong>Pick your first profile to create below!</strong></h5</p>
</div>
</div>

<div class="row align-items-center justify-content-center">
<div class="row">
<p>New business profile <%= link_to 'New Business', new_business_path, class: 'btn btn-danger' %> </p>
</div>
</div>



<div class="row align-items-center justify-content-center">
<div class="row">
<p>New personal profile <%= link_to 'New Personal', new_personal_path, class: 'btn btn-danger'%> </p>
</div>
</div>
</div>